//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceProceeding
    {
        public int ConfID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public int CopiesTotal { get; set; }
        public int CopiesAvailable { get; set; }
        public int CopiesOut { get; set; }
        public string SubjectArea { get; set; }
        public string YearOfPublication { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> ConfNumberID { get; set; }
        public string ShelfNumber { get; set; }
        public string Status { get; set; }
    }
}
